# Generated by Django 3.0.3 on 2020-08-20 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0006_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cart',
        ),
        migrations.AddField(
            model_name='account',
            name='cart',
            field=models.ManyToManyField(blank=True, editable=False, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
