# Generated by Django 3.0.3 on 2020-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_store', '0003_auto_20200820_2143'),
        ('User', '0007_auto_20200820_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='user_cart', to='Book_store.Book'),
        ),
    ]
