# Generated by Django 3.0.3 on 2020-08-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20200820_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cart',
        ),
    ]
